import type { DenoiseRules } from "./denoise";

export const DEFAULT_DENOISE: DenoiseRules = {
  denylistExact: new Set([
    "postcss",
    "autoprefixer",
    "eslint",
    "eslint-config-next",
    "prettier",
    "ts-node",
    "tsx",
  ]),
  denylistPrefix: ["@types/"],
  groups: {
    "clsx": "shadcn/ui",
    "tailwind-merge": "shadcn/ui",
    "class-variance-authority": "shadcn/ui",
    "tailwindcss-animate": "shadcn/ui",
    "lucide-react": "shadcn/ui",
    "cmdk": "shadcn/ui",
    "vaul": "shadcn/ui",
    "sonner": "shadcn/ui",
    "@radix-ui/react-dialog": "shadcn/ui",
    "@radix-ui/react-dropdown-menu": "shadcn/ui",
    "@radix-ui/react-popover": "shadcn/ui",
    "@radix-ui/react-tabs": "shadcn/ui",
    "@radix-ui/react-tooltip": "shadcn/ui",
    "@radix-ui/react-select": "shadcn/ui",
    "@radix-ui/react-accordion": "shadcn/ui",
    "@radix-ui/react-avatar": "shadcn/ui",
    "@radix-ui/react-checkbox": "shadcn/ui",
    "@radix-ui/react-label": "shadcn/ui",
    "@radix-ui/react-slot": "shadcn/ui",
    "@radix-ui/react-switch": "shadcn/ui",
    "@radix-ui/react-toast": "shadcn/ui",
  },
};
